# -*- coding: utf-8 -*-
"""Course 1 - Week 1 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBcA0WwwWhUxx5kQe9KASupvdBmxif5j
"""

pip install turicreate

pip freeze

"""## Importing the data
- Directly import the zip file without extracting
- Create a new folder named people_wiki.sframe
- Extract the files into the folder that we created using **zipfile** module
"""

pip install zipfile36 #Used to extract the zip file

#Steps to extract zip file in Python
import zipfile

target = '/content/-q2dp-IAEemnvhJSBz-0XA_9625a0851f91403da0239b66c8e2bed8_people_wiki.sframe.zip'
handle = zipfile.ZipFile(target)
handle.extractall('/content/people_wiki.sframe/')
handle.close()

import turicreate

sf = turicreate.SFrame('/content/people_wiki.sframe/people_wiki.sframe')

sf

"""#### 1) Write some description on the above table for first question's answer"""

sf  #2)Number of rows and columns are given at the bottom of the table

sf.tail() #3)Last row gives the answer

sf.print_rows(3,3,3000) #4)Search for honored word and you will find the answer

sf['text'].sort() #5)Sort the text column